# Find all the information you need at http://dev.thomasvdbulk.nl/KoTH/

# To grab your own timezone go to: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

global:
  schedule-timezone: "Europe/Amsterdam"
  use-playermoveevent: false
  pre-broadcast: 0
  helpcommand:
    - "&8========> &2Koth &8<========"
    - "&a/koth list &7Shows all available koths"
    - "&a/koth loot &7Shows the loot for the upcoming koth"
    - "&a/koth schedule &7Shows the schedule for koths"

loot:
  default: ""
  randomize: true
  default-amount: 5
  randomize-amount: false
  can-use-same-items: true
  remove-after: 0
  drop-on-removal: false
  give-instantly: false

koth:
  knockTime: 0
  minimum-players: 0

scoreboard:
  use-scoreboard: true
  use-old-scoreboard: false
  scoreboard:
    title: "&a&l%koth%"
    contents:
      - "&6&lTime Left:"
      - "&9%minutes_left%:%seconds_left%"
      - " "
      - "&6&lCoords:"
      - "&cX: &e%x%"
      - "&cZ: &e%z%"

factions:
  enable: false
  shouldCapAllAreas: false