# To grab your own timezone go to: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#
# The use-playermoveevent feature, when true, will use the PlayerMoveEvent (suprise!)
# This means that it will check if the player left the KOTH every single time the player moves
# This will end up with a VERY smooth koth experience, but is discouraged as again, it will trigger every time a player moves.
# You can turn it on if you like, see how it goes, and can always turn it off if lag occurs (a reload is required for this)
#
# One for all creates a single loot chest for all the koths
# Since this was request a lot, I added it in. It's disabled by default
#
# Randomize loot will make it so it will randomly generate the loot for you
# If you don't want this (You want all the items to be given in the chest)
# You should put this to false
#
# Setting the knock time to something higher than 0 will make the koth "freeze" for that amount of seconds
# This means that when someone gets knocked off the koth, it will take a moment before it can be capped again.
# This can be used to stop the spam messages in the chat.
#
# The randomize-amount-of-loot now chooses a random amount of loot of the stack you given.
#
# can-use-same-items is for if it can use the same item multiple times.
#
#
# For everything, a reload is required.
#
# Available placeholders (this is also used for the Lang.json),
# Note that not all placeholders are available for every message.
#
# %area% - The area for this message
# %player% - The player capping the area
# %world% - The world where the area is running
# %minutes% - The amount of minutes that this area is running
# %seconds% - The amount of seconds that this area is running
# %minutes_left% - The amount of minutes left for this area
# %seconds_left% - The amount of seconds left for this area
# %x% - X coordinate for the area
# %y% - Y coordinate for the area
# %z% - Z coordinate for the area
# %day% - Day of the schedule
# %time% - The time of the schedule
# %length% - The length of the area
# %id% - Schedule ID
# %date% - The current date
# %command% - This is the command for the help menu
# %command_info% - This is the description of the command for help menu
# %maxtime% - The maximal time in minutes the koth will run



schedule-timezone: "Europe/Amsterdam"
use-scoreboard: true
use-playermoveevent: false
one-for-all: false
amount-of-loot: 5
randomize-loot: true
randomize-amount-of-loot: false
can-use-same-items: true
knockTime: 0

scoreboard:
  title: "&a&l%area%"
  contents:
    - "&6&lTime Left:"
    - "&9%minutes_left%:%seconds_left%"
    - " "
    - "&6&lCoords:"
    - "&cX: &e%x%"
    - "&cZ: &e%z%"