# Find all the information you need at http://dev.thomasvdbulk.nl/KoTH/

# To grab your own timezone go to: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

global:
  use-cache: false
  debug: false
  multiplekothsatonce: true
  schedule-show-current-day-only: false
  schedule-timezone: "Europe/Amsterdam"
  minuteoffset: 0
  startweekminuteoffset: 0
  use-playermoveevent: false
  pre-broadcast: 0
  nocap-broadcast-interval: 30
  helpcommand:
    - "&8========> &2Koth &8<========"
    - "&a/koth list &7Shows all available koths"
    - "&a/koth loot &7Shows the loot for the upcoming koth"
    - "&a/koth schedule &7Shows the schedule for koths"

loot:
  default: ""
  randomize: true
  default-amount: 5
  randomize-amount: false
  can-use-same-items: true
  remove-after: 0
  drop-on-removal: false
  give-instantly: false
  commands:
    enabled: false
    changeingame: false
    needop: true

hooks:
  vanishnopacket: true
  factions: true
  kingdoms: true
  featherboard:
    enabled: false
    board: "koth"
    range: 100 # -1 to disable it
    rangemargin: 5

koth:
  default-capturetype: "" # set this to your desired capture type
  knockTime: 0
  minimum-players: 0

scoreboard:
  characterlimit: 16
  charactertitlelimit: 16
  use-scoreboard: true
  use-old-scoreboard: false
  default:
    title: "&a&l%koth%"
    contents:
      - "&6&lTime Left:"
      - "&9%ml%:%sl%"
      - " "
      - "&6&lCoords:"
      - "&cX: &e%x%"
      - "&cZ: &e%z%"
  conquest:
    title: "&a&l%koth%"
    contents:
      - "&6&lTime Left:"
      - "&9%ml%:%sl%"
      - " "
      - "&6&lCoords:"
      - "&cX: &e%x%"
      - "&cZ: &e%z%"