name: KoTH
main: subside.plugins.koth.Koth
version: 1.1.1
author: SubSide
commands:
  koth:
    description: Gives access to koth
permissions:
  koth.admin:
    description: Allows you to configure koths
    default: op
  koth.schedule:
    description: Allows you to schedule koths
    default: true
  koth.list:
    description: Allows you to see the list of koths
    default: true
  koth.loot:
    description: Allows you to see the loot
    default: true
  koth.info:
    description: Allows you to see the loot
    default: true