name: KoTH
main: subside.plugins.koth.Koth
version: 1.1.6 BETA v2
author: SubSide
softdepend: [Multiverse-Core]
commands:
  koth:
    description: Gives access to koth
permissions:
  koth.admin:
    description: Allows you to configure koths
    default: op
  koth.schedule:
    description: Allows you to schedule koths
    default: true
  koth.list:
    description: Allows you to see the list of koths
    default: true
  koth.loot:
    description: Allows you to see the loot
    default: true
  koth.info:
    description: Allows you to use koth info
    default: true
  koth.bypass:
    description: Allows you to bypass the blocking of chest opening and breaking.
    default: op